Test that protocol-integration-tests can run and pass
Signed-off-by: Jeff Kennedy <jeffk@kiva.org>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,6 +37,56 @@ jobs:
             docker stop $(docker ps -aq)
             docker-compose down
 
+  protocol-integration-tests:
+    machine:
+      image: ubuntu-1604:201903-01
+    steps:
+      - run:
+          name: Pull protocol-integration-tests
+          command: git clone https://github.com/kiva/protocol-integration-tests ./
+      - run:
+          name: Setup environment
+          command: |
+            ./scripts/setup_env.sh
+            echo $AUTH0_ENV | base64 --decode >> .env
+            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
+      - run:
+          name: Node npm setup
+          command: |
+            nvm install v14.15.1
+            node -v
+            nvm alias default v14.15.1
+      - run:
+          name: Get ACAPy
+          command: docker pull bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
+      - run:
+          name: Override for gateway image
+          command: ./scripts/setup_override.sh -r guardian-bio-auth -s bio_auth_service,bioanalyzer_service -f docker-compose.yml -e scripts/useDummyEnvFiles.sh
+      - run:
+          name: Start docker compose and wait for readiness
+          command: |
+            docker system prune -f
+            docker-compose -f docker-compose.yml build --no-cache
+            docker-compose -f docker-compose.yml up -d
+            sleep 20
+            docker-compose -f docker-compose.yml logs
+      - run:
+          name: Healthcheck services
+          command: ./scripts/healthstack.sh
+      - run:
+          name: Setup integration tests
+          command: |
+            npm install
+            ./scripts/setup_fixtures.sh
+      - run:
+          name: Running integration tests
+          command: |
+            if ! npm run test ; then
+              echo "Tests failed. Server logs:";
+              docker-compose -f docker-compose.yml logs;
+              exit 1;
+            fi
+
 workflows:
   build-test-deploy:
     jobs:
@@ -44,9 +94,18 @@ workflows:
           filters: # run for all branches AND tags
             tags:
               only: /.*/
+      - protocol-integration-tests:
+          context:
+            - integration-test-context
+          requires:
+            - build-and-test
+          filters: # only run for semver tagged versions
+            tags:
+              only: /.*/
       - docker/publish:
           requires:
             - build-and-test
+            - protocol-integration-tests
           filters: # only run for semver tagged versions
             tags:
               only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
@@ -68,6 +127,7 @@ workflows:
       - docker/publish:
           requires:
             - build-and-test
+            - protocol-integration-tests
           filters: # only run for semver tagged versions
             tags:
               only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
